#!/usr/bin/bash
set -euo pipefail

# Executes the data seeding workload for one site.
# All three insert workloads (accounts, transactions, collections) run simultaneously
# from a single config file generated by gen-harness.sh.
#
# Run gen-harness.sh first to generate the configs consumed by this script.

usage() {
  cat <<'EOF'
Usage:
  ./seed-data.sh [options] [/path/to/SimRunner.jar]

Options:
  --harness-dir DIR   Directory containing generated configs (default: harness)
  --site N            Site index to seed (selects seed-site-N.json).
                      Defaults to 1. Use the value matching this machine's --site
                      when gen-harness.sh was run with --sites > 1.
  -n, --dry-run       Print resolved config path and exit without running SimRunner.
  -h, --help          Show this help.

The SimRunner.jar path can also be supplied via the SIMRUNNER_JAR environment variable.
EOF
}

HARNESS_DIR="harness"
SITE_INDEX=1
JAR_PATH="${SIMRUNNER_JAR:-}"
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --harness-dir)  HARNESS_DIR="$2"; shift 2 ;;
    --site)         SITE_INDEX="$2";  shift 2 ;;
    -n|--dry-run)   DRY_RUN=1;        shift ;;
    -h|--help)      usage; exit 0 ;;
    *)
      if [[ -z "${JAR_PATH}" ]]; then
        JAR_PATH="$1"; shift
      else
        echo "Unexpected argument: $1"; usage; exit 1
      fi
      ;;
  esac
done

if [[ "${DRY_RUN}" -eq 0 ]] && [[ -z "${JAR_PATH}" ]]; then
  echo "Error: provide SimRunner.jar as a positional argument or via SIMRUNNER_JAR."
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "${SCRIPT_DIR}"

SEED_CONFIG="${HARNESS_DIR}/seed-site-${SITE_INDEX}.json"

[[ -f "${SEED_CONFIG}" ]] || \
  { echo "Config not found: ${SEED_CONFIG}  (run gen-harness.sh first)"; exit 1; }

if [[ "${DRY_RUN}" -eq 1 ]]; then
  echo "==> Dry run: would execute: java -jar <SimRunner.jar> ${SEED_CONFIG}"
  exit 0
fi

echo "==> Seeding site ${SITE_INDEX} — accounts, transactions, and collections (${SEED_CONFIG})"
java -jar "${JAR_PATH}" "${SEED_CONFIG}"

echo "==> Seeding complete (site ${SITE_INDEX})."
